/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MusicImport } from './routes/Music'
import { Route as GeneralImport } from './routes/General'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MusicRoute = MusicImport.update({
  id: '/Music',
  path: '/Music',
  getParentRoute: () => rootRoute,
} as any)

const GeneralRoute = GeneralImport.update({
  id: '/General',
  path: '/General',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/General': {
      id: '/General'
      path: '/General'
      fullPath: '/General'
      preLoaderRoute: typeof GeneralImport
      parentRoute: typeof rootRoute
    }
    '/Music': {
      id: '/Music'
      path: '/Music'
      fullPath: '/Music'
      preLoaderRoute: typeof MusicImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/General': typeof GeneralRoute
  '/Music': typeof MusicRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/General': typeof GeneralRoute
  '/Music': typeof MusicRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/General': typeof GeneralRoute
  '/Music': typeof MusicRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/General' | '/Music'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/General' | '/Music'
  id: '__root__' | '/' | '/General' | '/Music'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneralRoute: typeof GeneralRoute
  MusicRoute: typeof MusicRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneralRoute: GeneralRoute,
  MusicRoute: MusicRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/General",
        "/Music"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/General": {
      "filePath": "General.tsx"
    },
    "/Music": {
      "filePath": "Music.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
